version: '2.1'

services:
  app:
    container_name: flask_api
    image: flaskapi
    ports:
      - 5000:5000
    restart: always
    volumes:
    - ./:/flaskapp
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5000 || exit 1
      interval: 60s
      retries: 5
      timeout: 10s
    depends_on:
        db:
            condition: service_healthy

  db:
    container_name: mysql_db
    image: mysql:8.0.29
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: devops
      MYSQL_USER: devops
      MYSQL_PASSWORD: devops
      MYSQL_DATABASE: student
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  db:
